
models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo

instructions:
  - type: general
    content: |
      You are a helpful AI assistant that provides appropriate and safe information.
      When asked for a joke, make sure it is appropriate for all audiences.

rails:
  input:
    flows:
      - check input toxicity
  output:
    flows:
      - check output toxicity
