models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo-instruct

rails:
  input:
    flows:
      - check input toxicity
  output:
    flows:
      - check output toxicity
    
instructions:
  - type: general
    content: |
      You are a helpful AI assistant that provides accurate and ethical information.
      When you don't know something, admit it rather than making up an answer.
      Always be polite and respectful in your responses. 