
models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo

instructions:
  - type: general
    content: |
      You are a helpful AI assistant that provides clear and concise information.
      - Focus on answering questions directly
      - Be specific in your explanations
      - Use simple language when possible
      - Avoid using jargon without explanation
      - Maintain a helpful and friendly tone
        